AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates an ECS Cluster, ECS Service (with X-Ray sidecar),
  Auto-Scaling, and a CloudWatch Alarm in a VPC.

Parameters:
  ImageUri:
    Type: String
  ClusterName:
    Type: String
    Default: micro-service-cluster
    Description: Name of the ECS Cluster to create/use
  ServiceName:
    Type: String
    Default: micro-service-service
    Description: Name of the ECS Service to create

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC to launch into
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Two or more private subnets for Fargate
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security Group(s) for task ENIs

Resources:

  # ──────────────────────────────────────────────────────────────────────────────
  # 1) ECS Cluster (so Service has a cluster to attach to)
  MyCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName

  # ──────────────────────────────────────────────────────────────────────────────
  # 2) IAM Role for ECS Task Execution (with X-Ray write access)
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-task-exec-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        # Pull images, write to CloudWatch Logs
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        # Allow X-Ray daemon to send traces
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess

  # ──────────────────────────────────────────────────────────────────────────────
  # 3) ECS Task Definition (with X-Ray sidecar)
  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${ServiceName}-task
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: "256"
      Memory: "512"
      ContainerDefinitions:
        - Name: xray-daemon
          Image: public.ecr.aws/xray/aws-xray-daemon:latest
          Essential: false
          PortMappings:
            - ContainerPort: 2000
              Protocol: udp
        - Name: app
          Image: !Ref ImageUri
          Environment:
            - Name: AWS_XRAY_DAEMON_ADDRESS
              Value: "127.0.0.1:2000"
          PortMappings:
            - ContainerPort: 3000

  # ──────────────────────────────────────────────────────────────────────────────
  # 4) ECS Service (depends on the cluster being created first)
  MyService:
    Type: AWS::ECS::Service
    DependsOn: MyCluster
    Properties:
      Cluster: !Ref MyCluster
      ServiceName: !Ref ServiceName
      DesiredCount: 1
      TaskDefinition: !Ref MyTaskDefinition
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:        !Ref SubnetIds
          SecurityGroups: !Ref SecurityGroupIds
          AssignPublicIp: ENABLED

  # ──────────────────────────────────────────────────────────────────────────────
  # 5) Application Auto Scaling – Scalable Target
  #    Service must exist before registering as scalable target
  MyScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: MyService
    Properties:
      ServiceNamespace: ecs
      ResourceId: !Sub service/${ClusterName}/${ServiceName}
      ScalableDimension: ecs:service:DesiredCount
      MinCapacity: 1
      MaxCapacity: 10

  # ──────────────────────────────────────────────────────────────────────────────
  # 6) Application Auto Scaling – Target Tracking Policy (CPU)
  CpuScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: CpuScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref MyScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 60.0
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 60
        ScaleOutCooldown: 60

  # ──────────────────────────────────────────────────────────────────────────────
  # 7) CloudWatch Alarm (High CPU)
  HighCpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: HighCPUUtilization
      Namespace: AWS/ECS
      MetricName: CPUUtilization
      Dimensions:
        - Name: ClusterName
          Value: !Ref ClusterName
        - Name: ServiceName
          Value: !Ref ServiceName
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold

Outputs:
  ClusterArn:
    Description: ARN of the ECS Cluster
    Value: !GetAtt MyCluster.Arn

  ServiceArn:
    Description: ARN of the ECS Service
    Value: !Ref MyService
